name: 'Clean Lambda Versions'
description: 'Deletes older lambda versions'
author: 'Kerry Sheldon'
inputs:
  function_name:
    required: true
    description: 'name of lambda function to clean'
  number_to_keep:
    required: true
    description: 'number of versions to maintain'
  delete_versions_with_alias:
    required: false
    default: false
    description: 'allow to delete versions associated with an alias'
runs:
  using: 'node20'
  main: 'dist/index.js'
